name: run
on: [ push ]
jobs:
  run:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            15    # Latest version
        ]
        # and run on both Linux, Windows, and Mac
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '15'
      - name: Make gradle wrapper executable
        run: chmod +x gradlew
      - name: Build bot
        run: ./gradlew shadowJar
      - name: Move to build/libs dir
        run: cd /build/libs
      - name: Run shadow jar file
        run: java -jar fst-bot-1.0-SNAPSHOT-shadow.jar -token"${{ secrets.DISCORD_TOKEN }}"
